### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ADchae**
hey I'm trying to upload my code

### CODE REVIEW

**Review by QuinnRana — CHANGES_REQUESTED** [review]
Hey you need to put this in your own directory because this is in index.html which is the front of the site and your code is for your own directory/section

**Comment by ADchae** [comment]
I think i did it but its asking for another pull request

**Comment by QuinnRana** [comment]
Yea you have to redirect it to your directory and you have this directed towards the index.html directory

**Review by QuinnRana — CHANGES_REQUESTED** [review]
still attached to main code

**Pull request closed without merging**
